spring.application.name=TrabajoBackEnd

spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-quiet-field-a57xaqj6.us-east-2.aws.neon.tech:5432/dbTF
spring.datasource.username=dbTF_owner
spring.datasource.password=r4jkKqQLvwf9

server.port=8084
jwt.secret=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIZF9zUzoKokFoAUXj70pnEKCcdh98wV
P5xBcKhsVUP8pAZFkustM87khx/2G8GY20OMGBdm52v5dtDDXilyuDMCAwEAAQ==
